connector.name=iceberg
iceberg.catalog.type=jdbc

# 1. Connection URL (Added search_path for immediate schema access)
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://postgres:5432/iceberg?options=-c%20search_path%3Diceberg,public
iceberg.jdbc-catalog.connection-user=${ENV:DB_USER}
iceberg.jdbc-catalog.connection-password=${ENV:DB_PASSWORD}
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver

# 2. Catalog Identity (Crucial for newer Trino versions)
# This forces Trino to create the 'iceberg_tables' and 'iceberg_namespaces' tables
iceberg.jdbc-catalog.catalog-name=crypto_catalog
iceberg.jdbc-catalog.default-warehouse-dir=s3://bronze/warehouse

# 3. Storage Settings (MinIO)
fs.native-s3.enabled=true
s3.endpoint=http://host.docker.internal:9000
s3.region=us-east-1
s3.path-style-access=true
s3.aws-access-key=${ENV:MINIO_ACCESS_KEY}
s3.aws-secret-key=${ENV:MINIO_SECRET_KEY}